# -*- coding: utf-8 -*-
"""Копия блокнота "image_classification.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xfTBBotoJTkDENqfmXImvbhNdWGw3SYI
"""

from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils
import numpy as np

#Подготовка данных
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

x_train = x_train.reshape(60000, 784)
x_train = x_train / 255

y_train = utils.to_categorical(y_train, 10)
classes = ['футболка', 'брюки', 'свитер', 'платье', 'пальто', 'туфли', 'рубашка', 'кроссовки', 'сумка', 'ботинки']

#Создание модели
model = Sequential()

#Создание слоев для модели
model.add(Dense(800, input_dim=784, activation="relu"))
model.add(Dense(10, activation="softmax"))

#Компиляция модели
model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics=["accuracy"])

print(model.summary())

#Обучение сети
model.fit(x_train,
          y_train,
          batch_size=200,
          epochs=100,
          verbose=1)

predictions = model.predict(x_train)
print(prediction[0])
print(np.argmax(prediction[0]))
print(np.argmax(np.argmax(y_train[0])))